github.com:
    users:
        Maarkas:
            oauth_token: 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
    git_protocol: ssh
    user: Maarkas
    oauth_token: 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
